# Generated by Django 4.0.1 on 2022-02-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venu Name')),
                ('age', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, verbose_name='Student Email')),
                ('course', models.TextField(max_length=200)),
            ],
        ),
    ]
