# Generated by Django 4.0.1 on 2022-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_content1',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_content2',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_content3',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contentname1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contentname2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contentname3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
